--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2024-04-08 23:30:27

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3339 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 42143)
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    balance numeric(38,2)
);


ALTER TABLE public.client OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 42142)
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 25739)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 42176)
-- Name: operation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.operation (
    id_operation integer NOT NULL,
    client_id bigint NOT NULL,
    type_operation integer,
    amount numeric(38,2),
    time_operation timestamp(6) without time zone
);


ALTER TABLE public.operation OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 42175)
-- Name: operation_id_operation_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.operation ALTER COLUMN id_operation ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operation_id_operation_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 33906)
-- Name: operation_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.operation_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.operation_seq OWNER TO postgres;

--
-- TOC entry 3331 (class 0 OID 42143)
-- Dependencies: 218
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.client (id, balance) FROM stdin;
3200	31936.00
1000	50700.00
\.


--
-- TOC entry 3333 (class 0 OID 42176)
-- Dependencies: 220
-- Data for Name: operation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.operation (id_operation, client_id, type_operation, amount, time_operation) FROM stdin;
25	1000	1	400.00	2024-04-08 22:07:22.592
26	1000	2	-600.00	2024-04-08 22:07:32.409
27	3200	3	-2000.00	2024-04-08 22:08:00.579
28	1000	4	2000.00	2024-04-08 22:08:00.584
29	3200	3	-2000.00	2024-04-08 22:38:47.02
30	1000	4	2000.00	2024-04-08 22:38:47.086
\.


--
-- TOC entry 3340 (class 0 OID 0)
-- Dependencies: 217
-- Name: client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.client_id_seq', 1, false);


--
-- TOC entry 3341 (class 0 OID 0)
-- Dependencies: 215
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hibernate_sequence', 6, true);


--
-- TOC entry 3342 (class 0 OID 0)
-- Dependencies: 219
-- Name: operation_id_operation_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operation_id_operation_seq', 30, true);


--
-- TOC entry 3343 (class 0 OID 0)
-- Dependencies: 216
-- Name: operation_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operation_seq', 1, false);


--
-- TOC entry 3182 (class 2606 OID 42147)
-- Name: client pk_client; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT pk_client PRIMARY KEY (id);


--
-- TOC entry 3184 (class 2606 OID 42180)
-- Name: operation pk_operation; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT pk_operation PRIMARY KEY (id_operation);


--
-- TOC entry 3185 (class 2606 OID 42181)
-- Name: operation operation_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT operation_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client(id);


-- Completed on 2024-04-08 23:30:28

--
-- PostgreSQL database dump complete
--

